### ISSUE TITLE
error about reading feats while training with TIMIT_liGRU_mfcc.cfg

### ISSUE THREAD

**Issue by MXuer** [mravanelli/pytorch-kaldi#124]
when I trained with TIMIT_MLP_mfcc_basic.cfg, there was no problem. But I changed the cfg with TIMIT_liGRU_mfcc.cfg, it can't not generate the dict for name and feats. The error is as follows:
Epoch 0 / 23
Training TIMIT_tr chunk = 1 / 5
exp/TIMIT_liGRU_mfcc/exp_files/train_TIMIT_tr_ep000000000000000000000000_ck00000_mfcc.lst
<generator object read_mat_ark at 0x7fa8fd461cd0>
{}
[]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/export/home/duhu/anaconda3/envs/py27/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/export/home/duhu/anaconda3/envs/py27/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/export/home/duhu/pytorch-kaldi/data_io.py", line 209, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/export/home/duhu/pytorch-kaldi/data_io.py", line 129, in load_chunk
    [data_name,data_set,data_lab,end_index]=load_dataset(fea_scp,fea_opts,lab_folder,lab_opts,left,right, max_sequence_length, output_folder, fea_only)
  File "/export/home/duhu/pytorch-kaldi/data_io.py", line 83, in load_dataset
    fea_conc,lab_conc = zip(*fea_sorted)
ValueError: need more than 0 values to unpack

[]
Traceback (most recent call last):
  File "run_exp.py", line 198, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/export/home/duhu/pytorch-kaldi/core.py", line 83, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

the error happened at data_io.py line 19.
Would you give me some advice? Thank you !

**Comment by MXuer** [comment]
I already find the errors. Thank you for the project.

**Comment by PeiyanFlying** [comment]
hello, I have meet up with the same problem as you, so what's the error? 
Many thanks!
