### ISSUE TITLE
Cuda related issue

### ISSUE THREAD

**Issue by Subash33** [mravanelli/pytorch-kaldi#136]
Hello,
My GPU has cuda V7.5.17 , I see in the documentation that the pytorch-kaldi is tested with Cuda 8.0 > , Running liGRU models without CUDA set TRUE is taking forever, so i am trying to see if CUDA helps. However, I get the following error

RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51

At the moment I am asked not to make any changes in the GPU so I am reluctant to update cuda, do you think this error will be solved by just updating cuda to 10.0 version? 

Subash

**Comment by TParcollet** [comment]
Hi ! Well don't you have more logs? PyTorch-Kaldi hasn't been tested with Cuda < 8.0 since 7.5 has been released in 2015. I don't know if the error is related though, more logs are needed.

**Comment by Subash33** [comment]
Hi,
This is what I get:
Traceback (most recent call last):
  File "run_exp.py", line 195, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/subash/pytorch-kaldi/core.py", line 105, in run_nn
    [nns,costs]=model_init(inp_out_dict,model,config,arch_dict,use_cuda,multi_gpu,to_do)
  File "/home/subash/pytorch-kaldi/utils.py", line 1691, in model_init
    net.cuda()
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51

**Comment by TParcollet** [comment]
Ok, is it working if you try a minimal pytorch code ? Like a very small model (outside of pytorch-kaldi) ?

**Comment by Subash33** [comment]
Hi,
Apologies again as this  is not pytorch-kaldi specific error. My CUDA outside pytorch-kaldi in itself is not working. torch.backends.cudnn.enabled returns True ,but torch.cuda.is_available() is returning false. So I should work on fixing that. 

Thank you.
