### ISSUE TITLE
When running TIMIT_SRU_fbank.cfg I get this error and have checked everything and cannot figure it out

### ISSUE THREAD

**Issue by jessybris** [mravanelli/pytorch-kaldi#198]
(base) user@user-Lenovo-ideapad-510-15IKB:~/Bureau/pytorch-kaldi$ python run_exp.py cfg/TIMIT_baselines/TIMIT_SRU_fbank.cfg
- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 30 ------------------------------
Training TIMIT_tr chunk = 1 / 5
Traceback (most recent call last):
  File "run_exp.py", line 224, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/user/Bureau/pytorch-kaldi/core.py", line 378, in run_nn
    [nns,costs]=model_init(inp_out_dict,model,config,arch_dict,use_cuda,multi_gpu,to_do)
  File "/home/user/Bureau/pytorch-kaldi/utils.py", line 1753, in model_init
    net=nn_class(config[arch_dict[inp1][0]],inp_dim)
  File "/home/user/Bureau/pytorch-kaldi/neural_networks.py", line 1761, in __init__
    rescale=self.rescale,
TypeError: __init__() got an unexpected keyword argument 'n_proj'
^CException ignored in: <module 'threading' from '/home/user/anaconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/home/user/anaconda3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/home/user/anaconda3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by TParcollet** [comment]
Hi do you have the latest pytorch-kaldi code? There is nothing at line 1761 in neural_networks.py.

**Comment by mravanelli** [comment]
Have you solved this issue?

**Comment by jessybris** [comment]
Hi ; thank you for your responses. I have not solved this problem. I have always the same error.

 (base) user@user-Lenovo-ideapad-510-15IKB:~/Bureau/pytorch-kaldi$ python run_exp.py cfg/TIMIT_baselines/TIMIT_SRU_fbank.cfg
- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 30 ------------------------------
Training TIMIT_tr chunk = 1 / 5
Traceback (most recent call last):
  File "run_exp.py", line 224, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/user/Bureau/pytorch-kaldi/core.py", line 378, in run_nn
    [nns,costs]=model_init(inp_out_dict,model,config,arch_dict,use_cuda,multi_gpu,to_do)
  File "/home/user/Bureau/pytorch-kaldi/utils.py", line 1753, in model_init
    net=nn_class(config[arch_dict[inp1][0]],inp_dim)
  File "/home/user/Bureau/pytorch-kaldi/neural_networks.py", line 1761, in __init__
    rescale=self.rescale,
TypeError: __init__() got an unexpected keyword argument 'n_proj'


I joint the " neural_networks.py" file.

[neural_networks.txt](https://github.com/mravanelli/pytorch-kaldi/files/4047209/neural_networks.txt)
