### ISSUE TITLE
Using SincNet for speech recognition

### ISSUE THREAD

**Issue by zdgithub** [mravanelli/pytorch-kaldi#34]
I want to train a model using SincNet, so I copy the data in`kaldi/egs/timit/s5/data` into my `pytorch-kaldi/quick_test/data` and edit the `save_raw_fea.py ` as follows:
```
lab_folder='quick_test/tri3_ali'
lab_opts='ali-to-pdf'
out_folder='raw_TIMIT_200ms/train'
wav_lst='/data/zhanghao/pytorch-kaldi/quick_test/data/train/wav.scp'
scp_file_out='quick_test/data/train/feats_raw.scp'
```
Note：Because I don't have the `wav_lst`,  I use the `wav.scp` which is originally from the `kaldi/egs/timit/s5/data/train`. Then when I ran the save_raw_fea.py, I got the error:
```
ali-to-pdf quick_test/exp_ali/tri3_ali/final.mdl ark:- ark:- 
LOG (ali-to-pdf[5.5.166~1-013489]:main():ali-to-pdf.cc:68) Converted 3696 alignments to pdf sequences.
Traceback (most recent call last):
  File "save_raw_fea.py", line 76, in <module>
    [fs,signal]=scipy.io.wavfile.read(sig_path)
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 193, in read
    fsize, is_big_endian = _read_riff_chunk(fid)
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 140, in _read_riff_chunk
    raise ValueError("Not a WAV file.")
ValueError: Not a WAV file.
```
Then I edited the line 75 as`sig_path=sig_file.split(' ')[4]` so that the sig_path was correct(e.g.`/data/zhanghao/kaldi/egs/timit/data/TIMIT/TRAIN/DR2/FAEM0/SI1392.WAV` ). 
I think the datas which come from timit are all wav files, so I don't know why the error occurred.

**Comment by nimz** [comment]
If doing this, should also not divide by 32768 as the sphere files are already in floating point format.

**Comment by nimz** [comment]
If doing this, should also not divide by 32768 as the sphere files are already in floating point format.
