### ISSUE TITLE
MemoryError and IndexError: list index out of range

### ISSUE THREAD

**Issue by wentaoxandry** [mravanelli/pytorch-kaldi#58]
Hallo, I'm trying run pytorch-kaldi wit LRS2 databank, but I found this error, I have checked all paths are exists and the alignments are also exists. Please help me, thank you

- Reading config file......OK!
- Chunk creation......OK!

------------------------------ Epoch 00 / 23 ------------------------------
Training pretrain_train chunk = 1 / 10
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/media/wentao/wentaodisk/pytorch_kaldi/pytorch-kaldi/data_io.py", line 207, in read_lab_fea
    [data_name_fea,data_set_fea,data_end_index_fea]=load_chunk(fea_scp,fea_opts,lab_folder,lab_opts,cw_left,cw_right,max_seq_length, output_folder, fea_only)
  File "/media/wentao/wentaodisk/pytorch_kaldi/pytorch-kaldi/data_io.py", line 133, in load_chunk
    data_set=(data_set-np.mean(data_set,axis=0))/np.std(data_set,axis=0)
MemoryError

Traceback (most recent call last):
  File "/media/wentao/wentaodisk/pytorch_kaldi/pytorch-kaldi/run_exp.py", line 202, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/media/wentao/wentaodisk/pytorch_kaldi/pytorch-kaldi/core.py", line 81, in run_nn
    data_name=shared_list[0]
IndexError: list index out of range

Process finished with exit code 1

**Comment by wentaoxandry** [comment]
I have reset chuck number, now it works

**Comment by mravanelli** [comment]
Ok,
if you are using a HPC cluster you can also try to require more RAM memory
(using --mem flag in qsub or similar commands) because the chunk is
initially stored in RAM.
