### ISSUE TITLE
LSTM_cudnn 

### ISSUE THREAD

**Issue by hlthu** [mravanelli/pytorch-kaldi#83]
I was trying class `LSTM_cudnn`:

```
class LSTM_cudnn(nn.Module):
	def __init__(self, options,inp_dim):
		super(LSTM_cudnn, self).__init__()
		self.input_dim=inp_dim
		self.hidden_size=int(options['hidden_size'])
		self.num_layers=int(options['num_layers'])
		self.bias=strtobool(options['bias'])
		self.dropout=float(options['dropout'])
		self.bidirectional=strtobool(options['bidirectional'])
		self.lstm = nn.ModuleList([nn.LSTM(self.input_dim, self.hidden_size, self.num_layers, 
												bias=self.bias,dropout=self.dropout,bidirectional=self.bidirectional)])
		self.out_dim=self.hidden_size+self.bidirectional*self.hidden_size
			
	def forward(self, x):
		if self.bidirectional:
			h0 = torch.zeros(self.num_layers*2, x.shape[1], self.hidden_size)
			c0 = torch.zeros(self.num_layers*2, x.shape[1], self.hidden_size)
		else:
			h0 = torch.zeros(self.num_layers, x.shape[1], self.hidden_size)
			c0 = torch.zeros(self.num_layers, x.shape[1], self.hidden_size)
		if x.is_cuda:
			h0=h0.cuda()
			c0=c0.cuda()
		output, (hn, cn) = self.lstm[0](x, (h0, c0))
		return output
```
But it got the error:

```
Training WSJ0_mix_train chunk = 1 / 20
Traceback (most recent call last):
  File "run_exp.py", line 196, in <module>
    [data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict]=run_nn(data_name,data_set,data_end_index,fea_dict,lab_dict,arch_dict,config_chunk_file,processed_first,next_config_file)
  File "/home/huanglu/project/pytorch-kaldi/core.py", line 204, in run_nn
    outs_dict=forward_model(fea_dict,lab_dict,arch_dict,model,nns,costs,inp,inp_out_dict,max_len,batch_size,to_do,forward_outs)
  File "/home/huanglu/project/pytorch-kaldi/utils.py", line 1833, in forward_model
    outs_dict[out_name]=nns[inp1](outs_dict[inp2])
  File "/home/huanglu/usr/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huanglu/project/pytorch-kaldi/neural_networks.py", line 203, in forward
    output, (hn, cn) = self.lstm[0](x, (h0, c0))
  File "/home/huanglu/usr/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huanglu/usr/anaconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, tuple, list, int, int, float, bool, int, bool), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, tuple, list, int, int, float, bool, int, bool)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, tuple, list, int, int, float, bool, int, bool)

```

My pytorch version is 1.0.1.

**Comment by mravanelli** [comment]
Dear Lu,
thank you very much for pointing out this issue! The problem was that
the strtobool function was giving a integer instead of a boolean. This is
weird because with a previous version of python everything was working. I
anyway fixed the current version of the cudnn model. Does it work now?

**Comment by hlthu** [comment]
Thank you! It works now.

**Comment by hlthu** [comment]
I have compared the class `LSTM` and `LSTM_cudnn` with the following configs.

```proto
arch_name = LSTM_cudnn_layers
arch_proto = proto/LSTM.proto
arch_library = neural_networks
arch_class = LSTM
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
lstm_lay = 360,360,360,360
lstm_drop = 0.05*5|0.1*5|0.15*10|0.1*5|0.05*5,0.05*5|0.1*5|0.15*10|0.1*5|0.05*5,0.05*5|0.1*5|0.15*10|0.1*5|0.05*5,0.05*5|0.1*5|0.15*10|0.1*5|0.05*5
lstm_use_laynorm_inp = False
lstm_use_batchnorm_inp = False
lstm_use_laynorm = False,False,False,False
lstm_use_batchnorm = True,True,True,True
lstm_bidir = True
lstm_act = tanh,tanh,tanh,tanh
lstm_orthinit = True
arch_lr = 0.0005
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0
```

```
[architecture2]
arch_name = LSTM_layers
arch_proto = proto/LSTM_cudnn.proto
arch_library = neural_networks
arch_class = LSTM_cudnn
arch_pretrain_file = none
arch_freeze = False
arch_seq_model = True
hidden_size = 360
num_layers = 4
bias = True
batch_first = False
dropout = 0.2
bidirectional = True
arch_lr = 0.0005
arch_halving_factor = 0.5
arch_improvement_threshold = 0.001
arch_opt = rmsprop
opt_momentum = 0.0
opt_alpha = 0.95
opt_eps = 1e-8
opt_centered = False
opt_weight_decay = 0.0
```
`LSTM_cudnn` is musch faster than `LSTM`, but it performs worse on validation set, see figure below.
Also I notice that the class `LSTM` will use a shared LSTM cell for both directions when bidirectional is True and the components for dropout are different. Also, batch norm is applied to the output of linear transform of input. Are these the reason? (But when bidirectional `LSTM_cudnn` will have twice parameters as `LSTM`.) Besides, what can I do to avoid the overfiting of `LSTM_cudnn` , since I have already adopted dropout. Could you give me some advice? Thx. 

![loss](https://user-images.githubusercontent.com/15335988/56399020-4b493100-627e-11e9-954a-8a8a166db707.png)

**Comment by mravanelli** [comment]
Dear Lu,
thank you for doing these experiments.
Yes, our LSTM model is slower but leads to better results than the
LSTM_cudnn standard implementation. In fact, we carefully design our
networks to improve the speech recognition performance. For instance, batch
normalization is applied to feed-forward connections only, while recurrent
dropout applies the same mask to all the time steps. These simple
modifications lead to a remarkable performance improvement.

Best,

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
